---
# This is a sample database file for the DataMapper ORM
# depending on your installation of mysql you may need to 
# specify a username, password, host, or socket
development: &defaults
  adapter: mysql
  database: comic_development
  username: root
  host: localhost
  socket: /opt/local/var/run/mysql5/mysqld.sock
 
test:
  <<:       *defaults
  database: comic_test
 
 
production:
  <<:       *defaults
  database: production
 
rake:
  <<: *defaults