---
# This is a sample database file for the DataMapper ORM
# depending on your installation of mysql you may need to 
# specify a username, password, host, or socket
development: &defaults
  adapter:  mysql
  database: comic_development
  # username: 
  # password:
  # host:
  # socket:
 
test:
  <<:       *defaults
  database: comic_test
 
 
production:
  <<:       *defaults
  database: production
 
rake:
  <<: *defaults